name: xylophone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sound1.wav
    - assets/sound2.wav
    - assets/sound3.wav
    - assets/sound4.wav
    - assets/sound5.wav
    - assets/sound6.wav
    - assets/sound7.wav
    - images/bird.png
    - images/cat.png
    - images/cow.png
    - images/dog.png
    - images/donkey.png
    - images/lion.png
    - images/rooster.png

